### ISSUE TITLE
Crash on 0.44.0 with ZLUDA support

### ISSUE THREAD

**Issue by ryans233** [koharu-rs/koharu#442]
After updating koharu to 0.44.0, I tried enabling ZLUDA support by installing the AMD HIP SDK 7.1.0. 
Once "AMD-Software-PRO-Edition-26.Q1-Win11-For-HIP" was installed (checked all items except the display driver), I attempted to launch koharu, but it failed to start after finishing the ZLUDA download.

Running koharu.exe via cmd gave me the following console output:
```
C:\Users\Ryans233\AppData\Local\koharu>ℹ starting server  root=C:\Users\Ryans233\AppData\Local\Koharu  port=53769
ℹ HTTP server listening on http://127.0.0.1:53769
ℹ Experimental ZLUDA v6-preview.63 support enabled
✗ AssetNotFound("index.html")  log.target=tauri::manager  log.module_path=tauri::manager  log.file=C:\Users\runneradmin\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\tauri-2.10.3\src\manager\mod.rs  log.line=459
ℹ NVIDIA driver reports CUDA 13.0 support
ℹ GPU compute capability: 8.8
✗ Failed to build resources: CublasError(CUBLAS_STATUS_INTERNAL_ERROR)
```

Here is my system information:
```
CPU: AMD Ryzen 7 9800X3D
GPU: AMD Radeon RX 9070 XT
System: Windows 11 Pro 25H2 26200.8037
Driver: AMD Software: Adrenalin Edition 26.3.1
```

**Comment by mayocream** [comment]
@Map1en can you help here?

**Comment by ryans233** [comment]
I downloaded the latest Pre-release ```zluda-windows-8251f1e.zip``` from [ZLUDA/releases](https://github.com/vosen/ZLUDA/releases) and replaced the DLLs in ```%LOCALAPPDATA%\koharu\runtime\zluda``` (which previously held the ```zluda-windows-e070320.zip``` version). After that, it launched without any issues.

Then I tried translating a few manga chapters and noticed that the LLM step is significantly faster compared to the version without ZLUDA support, and the GPU usage has dropped quite a bit, too. Looks like it’s doing the trick!

```
C:\Users\Ryans233\AppData\Local\koharu>ℹ starting server  root=C:\Users\Ryans233\AppData\Local\Koharu  port=56867
ℹ HTTP server listening on http://127.0.0.1:56867
ℹ Experimental ZLUDA v6-preview.63 support enabled
ℹ NVIDIA driver reports CUDA 13.0 support
ℹ GPU compute capability: 8.8
✗ AssetNotFound("index.html")  log.target=tauri::manager  log.module_path=tauri::manager  log.file=C:\Users\runneradmin\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\tauri-2.10.3\src\manager\mod.rs  log.line=459
▶ init .........................................█████████████████████████████████████████████████████████     13µs  100%
▶ load  r=BlobRef("40d0f81cd9e728605526ae144b.. █████████████████████████████████████████████████████████      1ms  100%
▶ load  r=BlobRef("76b72367b3a572964dbac44604.. █████████████████████████████████████████████████████████      1ms  100%
▶ load  r=BlobRef("5b95a4bae63fdd742eebd00905.. █████████████████████████████████████████████████████████      1ms  100%
▶ load  r=BlobRef("48272575340efdbb3d6b7b55eb.. █████████████████████████████████████████████████████████      2ms  100%
▶ load  r=BlobRef("eab0991b527bd89d485af4cec1.. █████████████████████████████████████████████████████████      2ms  100%
▶ load  r=BlobRef("2636a6835437927678758ffc98.. █████████████████████████████████████████████████████████      1ms  100%
▶ load  r=BlobRef("4c4db497ecdd3ef924777d07d6.. █████████████████████████████████████████████████████████      1ms  100%
▶ load  r=BlobRef("f8c49d81d21a58ef61836de30d.. █████████████████████████████████████████████████████████      1ms  100%
```

**Comment by marios8543** [comment]
> I downloaded the latest Pre-release `zluda-windows-8251f1e.zip` from [ZLUDA/releases](https://github.com/vosen/ZLUDA/releases) and replaced the DLLs in `%LOCALAPPDATA%\koharu\runtime\zluda` (which previously held the `zluda-windows-e070320.zip` version). After that, it launched without any issues.
> 
> Then I tried translating a few manga chapters and noticed that the LLM step is significantly faster compared to the version without ZLUDA support, and the GPU usage has dropped quite a bit, too. Looks like it’s doing the trick!
> 
> ```
> C:\Users\Ryans233\AppData\Local\koharu>ℹ starting server  root=C:\Users\Ryans233\AppData\Local\Koharu  port=56867
> ℹ HTTP server listening on http://127.0.0.1:56867
> ℹ Experimental ZLUDA v6-preview.63 support enabled
> ℹ NVIDIA driver reports CUDA 13.0 support
> ℹ GPU compute capability: 8.8
> ✗ AssetNotFound("index.html")  log.target=tauri::manager  log.module_path=tauri::manager  log.file=C:\Users\runneradmin\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\tauri-2.10.3\src\manager\mod.rs  log.line=459
> ▶ init .........................................█████████████████████████████████████████████████████████     13µs  100%
> ▶ load  r=BlobRef("40d0f81cd9e728605526ae144b.. █████████████████████████████████████████████████████████      1ms  100%
> ▶ load  r=BlobRef("76b72367b3a572964dbac44604.. █████████████████████████████████████████████████████████      1ms  100%
> ▶ load  r=BlobRef("5b95a4bae63fdd742eebd00905.. █████████████████████████████████████████████████████████      1ms  100%
> ▶ load  r=BlobRef("48272575340efdbb3d6b7b55eb.. █████████████████████████████████████████████████████████      2ms  100%
> ▶ load  r=BlobRef("eab0991b527bd89d485af4cec1.. █████████████████████████████████████████████████████████      2ms  100%
> ▶ load  r=BlobRef("2636a6835437927678758ffc98.. █████████████████████████████████████████████████████████      1ms  100%
> ▶ load  r=BlobRef("4c4db497ecdd3ef924777d07d6.. █████████████████████████████████████████████████████████      1ms  100%
> ▶ load  r=BlobRef("f8c49d81d21a58ef61836de30d.. █████████████████████████████████████████████████████████      1ms  100%
> ```

can confirm this worked for me as well on an RX 9060XT (Driver 26.3.1). Thanks a ton!!

**Comment by versita** [comment]
Had the same issue with a RX 9070 XT. Replacing the DLLs worked for me, thanks.

**Comment by mayocream** [comment]
Thank you for finding the fix! I've pushed a commit to upgrade ZLUDA to the latest and triggered a new patch release (0.44.2)! https://github.com/mayocream/koharu/commit/23d97e552fb9d460ceb0d772c7823518efb36eef

**Comment by mayocream** [comment]
Please feel free to re-open this ticket if you still encounter the same issue!

**Comment by versita** [comment]
I tried the new release and it doesn't fix the issue. 

It looks like Koharu is using the wrong DLLs. In `%LOCALAPPDATA%\koharu\runtime\zluda`, I find the DLLs from the `trace` directory of the ZLUDA archive. It works fine when I use the DLLs from the root directory of the ZLUDA archive.

**Comment by mayocream** [comment]
> I tried the new release and it doesn't fix the issue.
> 
> It looks like Koharu is using the wrong DLLs. In `%LOCALAPPDATA%\koharu\runtime\zluda`, I find the DLLs from the `trace` directory of the ZLUDA archive. It works fine when I use the DLLs from the root directory of the ZLUDA archive.

Can you try 0.44.3 to see if that fixes it?

**Comment by versita** [comment]
> Can you try 0.44.3 to see if that fixes it?

Seems to be falling back on the CPU for me because it's still using the wrong nvcuda.dll. Swapped out for the correct one (which is 56.4 MB) and it works. The other DLLs seem to be correct.

```
ℹ starting server  root=C:\Users\xxxx\AppData\Local\Koharu  port=50253
ℹ HTTP server listening on http://127.0.0.1:50253/
ℹ Experimental ZLUDA v6-preview.64 support enabled

thread '<unnamed>' (20092) panicked at zluda_trace\src\lib.rs:1006:61:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[ZLUDA_TRACE] cuInit(...) -> UNKNOWN
[ZLUDA_TRACE]     Invalid CUDA library at path C:\Windows\System32\nvcuda.dll
⚠ Could not verify NVIDIA driver support for CUDA 13.0: cuInit failed with CUDA driver error code 999; falling back to CPU.
⚠ No GPU support detected; falling back to CPU. For better performance, ensure you have a compatible NVIDIA GPU with the latest drivers, or a recent Apple device with Metal support.

thread '<unnamed>' (20092) panicked at zluda_trace\src\lib.rs:1000:40:
explicit panic
[ZLUDA_TRACE] cuInit(...) -> UNKNOWN

**Comment by mayocream** [comment]
@versita can you try 0.44.4? 😿

**Comment by ryans233** [comment]
> [@versita](https://github.com/versita) can you try 0.44.4? 😿

0.44.4 works now.

**Comment by versita** [comment]
Yep, latest release works for me.
