### ISSUE TITLE
pipeline step failed: DriverError(CUDA_ERROR_NOT_FOUND, "error")

### ISSUE THREAD

**Issue by lekoOwO** [koharu-rs/koharu#580]
Was running with 9070XT, HIP installed.
Getting error:
```
> .\koharu.exe --debug
ℹ starting server  port=4000
ℹ Experimental ZLUDA v6-preview.65 support enabled

▶ init .........................................█████████████████████████████████████████████████████████     22µs  100%

▶ run ............................................██████████████████████████████████████████████████████████████    1.99s  100%
├ engine_load  engine=speech-bubble-segmentation  █████████████████████████████████████████████████████████████░    1.96s   98%
│ │ ℹ NVIDIA driver reports CUDA 13.0 support
│ │ ℹ GPU compute capability: 8.8
├ step  engine=speech-bubble-segmentation  page.. ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░█     34ms    2%
│ ⚠ pipeline step failed: DriverError(CUDA_ERROR_NOT_FOUND, "error")  engine=speech-bubble-segmentation  page=019dc777-9031-7020-b9e3-55b9c85e3ce8  step_index=0
```

**Comment by lekoOwO** [comment]
Update: 
After adding the `runtime\zluda` dir to PATH, error becomes:
```
> ℹ starting server  port=4000
ℹ Experimental ZLUDA v6-preview.65 support enabled

▶ init .........................................█████████████████████████████████████████████████████████     41µs  100%

▶ run ............................................██████████████████████████████████████████████████████████████    652ms  100%
├ engine_load  engine=speech-bubble-segmentation  ██████████████████████████████████████████████████████████████    652ms  100%
│ │ ℹ NVIDIA driver reports CUDA 13.0 support
│ │ ℹ GPU compute capability: 8.8
│ ⚠ pipeline step failed: CublasError(CUBLAS_STATUS_INTERNAL_ERROR)  engine=speech-bubble-segmentation  page=019dc777-9031-7020-b9e3-55b9c85e3ce8  step_index=0
```

**Comment by lekoOwO** [comment]
Update: trace
```
[ZLUDA_TRACE] cuModuleGetFunction(hfunc: 0x101dfbba0, hmod: 0x1e2082ab7a0, name: "affine_bf16") -> CUDA_ERROR_NOT_FOUND
[ZLUDA_TRACE] cuCtxGetCurrent(pctx: 0x1e2335e8340) -> CUDA_SUCCESS
[ZLUDA_TRACE] cuStreamWaitEvent(hStream: 0x0, hEvent: 0x1e2103993d0, Flags: 0) -> CUDA_SUCCESS
[ZLUDA_TRACE] cuCtxGetCurrent(pctx: 0x1e2335e8340) -> CUDA_SUCCESS
[ZLUDA_TRACE] cuStreamWaitEvent(hStream: 0x0, hEvent: 0x1e210398930, Flags: 0) -> CUDA_SUCCESS
[ZLUDA_TRACE] cuCtxGetCurrent(pctx: 0x1e2335e8340) -> CUDA_SUCCESS
[ZLUDA_TRACE] cuStreamSynchronize(hStream: 0x0) -> CUDA_SUCCESS
[ZLUDA_TRACE] cuMemFree_v2(dptr: 0x4094a0000) -> CUDA_SUCCESS
[ZLUDA_TRACE] cuCtxGetCurrent(pctx: 0x1e2335e8340) -> CUDA_SUCCESS
[ZLUDA_TRACE] cuEventDestroy_v2(hEvent: 0x1e2103993d0) -> CUDA_SUCCESS
[ZLUDA_TRACE] cuCtxGetCurrent(pctx: 0x1e2335e8340) -> CUDA_SUCCESS
[ZLUDA_TRACE] cuEventDestroy_v2(hEvent: 0x1e210398930) -> CUDA_SUCCESS
[ZLUDA_TRACE] cuGetErrorString(error: CUDA_ERROR_NOT_FOUND, pStr: "error") -> CUDA_SUCCESS
[ZLUDA_TRACE] cuGetErrorString(error: CUDA_ERROR_NOT_FOUND, pStr: "error") -> CUDA_SUCCESS
[ZLUDA_TRACE] cuGetErrorString(error: CUDA_ERROR_NOT_FOUND, pStr: "error") -> CUDA_SUCCESS

▶ run ............................................██████████████████████████████████████████████████████████████    4.10s  100%
├ engine_load  engine=speech-bubble-segmentation  ███████████████████████████████████████████████████████████░░░    3.89s   95%
│ │ ℹ NVIDIA driver reports CUDA 13.0 support
│ │ ℹ GPU compute capability: 8.8
├ step  engine=speech-bubble-segmentation  page.. ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░███    210ms    5%
│ ⚠ pipeline step failed: DriverError(CUDA_ERROR_NOT_FOUND, "error")  engine=speech-bubble-segmentation  page=019dc777-9031-7020-b9e3-55b9c85e3ce8  step_index=0
```

seems that `bf16` is the reason

**Comment by mayocream** [comment]
working on a fix now

**Comment by lekoOwO** [comment]
using v0.50.1, cannot identify the error since the app is crashing when trying __Identify__

BTW the official HIP should not be used because the official one does not support cudnn, use the unofficial one mentioned at `https://zluda.readthedocs.io/latest/hip_sdk.html`

**Comment by mayocream** [comment]
Fixed in 0.52.0 (coming) via https://github.com/mayocream/koharu/pull/582

**Comment by lekoOwO** [comment]
@mayocream  I'm still getting
```
[ZLUDA_TRACE] cuModuleLoadData(module: 0x1e7c9666560, image: 0x1e7c99e3120) -> CUDA_SUCCESS
[ZLUDA_TRACE]     Saved module to module_0002.ptx
[ZLUDA_TRACE]     Error parsing module, log has been written to module_0002.log
[ZLUDA_TRACE] cuModuleGetFunction(hfunc: 0xc4dd7fba80, hmod: 0x1e7c9666560, name: "affine_bf16") -> CUDA_ERROR_NOT_FOUND
[ZLUDA_TRACE] cuCtxGetCurrent(pctx: 0x1e7e20e66c0) -> CUDA_SUCCESS
[ZLUDA_TRACE] cuStreamWaitEvent(hStream: 0x0, hEvent: 0x1e7c98787c0, Flags: 0) -> CUDA_SUCCESS
[ZLUDA_TRACE] cuCtxGetCurrent(pctx: 0x1e7e20e66c0) -> CUDA_SUCCESS
[ZLUDA_TRACE] cuStreamWaitEvent(hStream: 0x0, hEvent: 0x1e7c9877280, Flags: 0) -> CUDA_SUCCESS
[ZLUDA_TRACE] cuCtxGetCurrent(pctx: 0x1e7e20e66c0) -> CUDA_SUCCESS
[ZLUDA_TRACE] cuStreamSynchronize(hStream: 0x0) -> CUDA_SUCCESS
[ZLUDA_TRACE] cuMemFree_v2(dptr: 0x4094a0000) -> CUDA_SUCCESS
[ZLUDA_TRACE] cuCtxGetCurrent(pctx: 0x1e7e20e66c0) -> CUDA_SUCCESS
[ZLUDA_TRACE] cuEventDestroy_v2(hEvent: 0x1e7c98787c0) -> CUDA_SUCCESS
[ZLUDA_TRACE] cuCtxGetCurrent(pctx: 0x1e7e20e66c0) -> CUDA_SUCCESS
[ZLUDA_TRACE] cuEventDestroy_v2(hEvent: 0x1e7c9877280) -> CUDA_SUCCESS
[ZLUDA_TRACE] cuGetErrorString(error: CUDA_ERROR_NOT_FOUND, pStr: "error") -> CUDA_SUCCESS
[ZLUDA_TRACE] cuGetErrorString(error: CUDA_ERROR_NOT_FOUND, pStr: "error") -> CUDA_SUCCESS
[ZLUDA_TRACE] cuGetErrorString(error: CUDA_ERROR_NOT_FOUND, pStr: "error") -> CUDA_SUCCESS
```
On v0.52.0

**Comment by mayocream** [comment]
> [@mayocream](https://github.com/mayocream) I'm still getting
> 
> ```
> [ZLUDA_TRACE] cuModuleLoadData(module: 0x1e7c9666560, image: 0x1e7c99e3120) -> CUDA_SUCCESS
> [ZLUDA_TRACE]     Saved module to module_0002.ptx
> [ZLUDA_TRACE]     Error parsing module, log has been written to module_0002.log
> [ZLUDA_TRACE] cuModuleGetFunction(hfunc: 0xc4dd7fba80, hmod: 0x1e7c9666560, name: "affine_bf16") -> CUDA_ERROR_NOT_FOUND
> [ZLUDA_TRACE] cuCtxGetCurrent(pctx: 0x1e7e20e66c0) -> CUDA_SUCCESS
> [ZLUDA_TRACE] cuStreamWaitEvent(hStream: 0x0, hEvent: 0x1e7c98787c0, Flags: 0) -> CUDA_SUCCESS
> [ZLUDA_TRACE] cuCtxGetCurrent(pctx: 0x1e7e20e66c0) -> CUDA_SUCCESS
> [ZLUDA_TRACE] cuStreamWaitEvent(hStream: 0x0, hEvent: 0x1e7c9877280, Flags: 0) -> CUDA_SUCCESS
> [ZLUDA_TRACE] cuCtxGetCurrent(pctx: 0x1e7e20e66c0) -> CUDA_SUCCESS
> [ZLUDA_TRACE] cuStreamSynchronize(hStream: 0x0) -> CUDA_SUCCESS
> [ZLUDA_TRACE] cuMemFree_v2(dptr: 0x4094a0000) -> CUDA_SUCCESS
> [ZLUDA_TRACE] cuCtxGetCurrent(pctx: 0x1e7e20e66c0) -> CUDA_SUCCESS
> [ZLUDA_TRACE] cuEventDestroy_v2(hEvent: 0x1e7c98787c0) -> CUDA_SUCCESS
> [ZLUDA_TRACE] cuCtxGetCurrent(pctx: 0x1e7e20e66c0) -> CUDA_SUCCESS
> [ZLUDA_TRACE] cuEventDestroy_v2(hEvent: 0x1e7c9877280) -> CUDA_SUCCESS
> [ZLUDA_TRACE] cuGetErrorString(error: CUDA_ERROR_NOT_FOUND, pStr: "error") -> CUDA_SUCCESS
> [ZLUDA_TRACE] cuGetErrorString(error: CUDA_ERROR_NOT_FOUND, pStr: "error") -> CUDA_SUCCESS
> [ZLUDA_TRACE] cuGetErrorString(error: CUDA_ERROR_NOT_FOUND, pStr: "error") -> CUDA_SUCCESS
> ```
> 
> On v0.52.0

what model are you using?

**Comment by lekoOwO** [comment]
> > [@mayocream](https://github.com/mayocream) I'm still getting
> > ```
> > [ZLUDA_TRACE] cuModuleLoadData(module: 0x1e7c9666560, image: 0x1e7c99e3120) -> CUDA_SUCCESS
> > [ZLUDA_TRACE]     Saved module to module_0002.ptx
> > [ZLUDA_TRACE]     Error parsing module, log has been written to module_0002.log
> > [ZLUDA_TRACE] cuModuleGetFunction(hfunc: 0xc4dd7fba80, hmod: 0x1e7c9666560, name: "affine_bf16") -> CUDA_ERROR_NOT_FOUND
> > [ZLUDA_TRACE] cuCtxGetCurrent(pctx: 0x1e7e20e66c0) -> CUDA_SUCCESS
> > [ZLUDA_TRACE] cuStreamWaitEvent(hStream: 0x0, hEvent: 0x1e7c98787c0, Flags: 0) -> CUDA_SUCCESS
> > [ZLUDA_TRACE] cuCtxGetCurrent(pctx: 0x1e7e20e66c0) -> CUDA_SUCCESS
> > [ZLUDA_TRACE] cuStreamWaitEvent(hStream: 0x0, hEvent: 0x1e7c9877280, Flags: 0) -> CUDA_SUCCESS
> > [ZLUDA_TRACE] cuCtxGetCurrent(pctx: 0x1e7e20e66c0) -> CUDA_SUCCESS
> > [ZLUDA_TRACE] cuStreamSynchronize(hStream: 0x0) -> CUDA_SUCCESS
> > [ZLUDA_TRACE] cuMemFree_v2(dptr: 0x4094a0000) -> CUDA_SUCCESS
> > [ZLUDA_TRACE] cuCtxGetCurrent(pctx: 0x1e7e20e66c0) -> CUDA_SUCCESS
> > [ZLUDA_TRACE] cuEventDestroy_v2(hEvent: 0x1e7c98787c0) -> CUDA_SUCCESS
> > [ZLUDA_TRACE] cuCtxGetCurrent(pctx: 0x1e7e20e66c0) -> CUDA_SUCCESS
> > [ZLUDA_TRACE] cuEventDestroy_v2(hEvent: 0x1e7c9877280) -> CUDA_SUCCESS
> > [ZLUDA_TRACE] cuGetErrorString(error: CUDA_ERROR_NOT_FOUND, pStr: "error") -> CUDA_SUCCESS
> > [ZLUDA_TRACE] cuGetErrorString(error: CUDA_ERROR_NOT_FOUND, pStr: "error") -> CUDA_SUCCESS
> > [ZLUDA_TRACE] cuGetErrorString(error: CUDA_ERROR_NOT_FOUND, pStr: "error") -> CUDA_SUCCESS
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > On v0.52.0
> 
> what model are you using?

It was `speech-bubble-segmentation`

**Comment by mayocream** [comment]
That’s very weird, I already gated the bf16 and cudnn path, and it works on a AMD GPU. Can you try compiling from source code and do some debugging?

**Comment by lekoOwO** [comment]
I've found the issue:
with ` zluda.exe --zluda-trace`, koharu does not know it is running in zluda, thus selecting BF16
I tried running it without wrapper and the __identify__ runs to about 25% and koharu crashed

**Comment by mayocream** [comment]
> I've found the issue: with ` zluda.exe --zluda-trace`, koharu does not know it is running in zluda, thus selecting BF16 I tried running it without wrapper and the **identify** runs to about 25% and koharu crashed

Try compiling from source code and run ‘bun dev’

**Comment by lekoOwO** [comment]
Update:
With v0.50.1 + Unofficial ROCm 0311 + zluda wrapper, the __identify__ succeed.

If without zluda wrapper (aka loads the built-in zluda) it fails.
With newer ROCm it fails (7.13.x ROCm has broken cusparse)
With v0.52.0 & zluda wrapper it fails (selects BF16)

I'm still working on compiling and I hope the info helps debugging

**Comment by lekoOwO** [comment]
emmm on CUDA 13.0 I get the error:
```
│ ⚠ pipeline step failed: CublasError(CUBLAS_STATUS_INTERNAL_ERROR)
   0: std::backtrace_rs::backtrace::win64::trace
             at /rustc/59807616e1fa2540724bfbac14d7976d7e4a3860/library\std\src\..\..\backtrace\src\backtrace\win64.rs:85
   1: std::backtrace_rs::backtrace::trace_unsynchronized
             at /rustc/59807616e1fa2540724bfbac14d7976d7e4a3860/library\std\src\..\..\backtrace\src\backtrace\mod.rs:66
   2: std::backtrace::Backtrace::create
             at /rustc/59807616e1fa2540724bfbac14d7976d7e4a3860/library\std\src\backtrace.rs:331
   3: std::backtrace::Backtrace::capture
             at /rustc/59807616e1fa2540724bfbac14d7976d7e4a3860/library\std\src\backtrace.rs:296
   4: candle_core::error::Error::bt
   5: <candle_core::cuda_backend::device::CudaDevice as candle_core::backend::BackendDevice>::new
   6: candle_core::device::Device::new_cuda
   7: koharu_ml::device
   8: koharu_ml::speech_bubble_segmentation::SpeechBubbleSegmentation::load_from_paths
   9: koharu_app::llm::Model::new
  10: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
  11: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
  12: koharu_app::ai::AiManager::start_codex_device_login::{{closure}}::{{closure}}
  13: koharu_rpc::routes::pipelines::start_pipeline::{{closure}}::{{closure}}
  14: tokio::runtime::task::harness::Harness<T,S>::poll
  15: tokio::runtime::scheduler::multi_thread::worker::<impl tokio::runtime::scheduler::multi_thread::handle::Handle>::schedule_option_task_without_yield
  16: tokio::runtime::context::scoped::Scoped<T>::set
  17: tokio::runtime::context::runtime::enter_runtime
  18: tokio::runtime::scheduler::multi_thread::worker::run
  19: tokio::runtime::task::core::Core<T,S>::poll
  20: tokio::runtime::task::harness::Harness<T,S>::poll
  21: tokio::runtime::blocking::pool::Inner::run
  22: std::sys::backtrace::__rust_begin_short_backtrace
  23: <&T as core::fmt::Debug>::fmt
  24: std::sys::thread::windows::impl$0::new::thread_start
             at /rustc/59807616e1fa2540724bfbac14d7976d7e4a3860/library\std\src\sys\thread\windows.rs:58
  25: BaseThreadInitThunk
  26: RtlUserThreadStart
  engine=speech-bubble-segmentation  page=019dc777-9031-7020-b9e3-55b9c85e3ce8  step_index=0
```

Try fixing but seems not that easy

**Comment by mayocream** [comment]
Can you try official HIP SDK? both 7.x and 6.x worth trying. In our Discord server, the other user shared that 0.52.0 have no issue with AMD GPU, so i guess it’s related to your setup.

**Comment by lekoOwO** [comment]
Using official ROCm 7.1:
```
No GPU support detected; falling back to CPU. For better performance, ensure you have a compatible NVIDIA GPU with the latest drivers, or a recent Apple device with Metal support.
```

With unofficial ROCm 7.12 20260311:
```
Experimental ZLUDA v6-preview.65 support enabled
<and with previous mentioned error>
```

**Comment by 0fbcb238c0** [comment]
Can confirm that ZLUDA does not work for me with ROCm 7.2.2. on linux

```
├ engine_load  engine=speech-bubble-segmentation ...
│ │ ℹ NVIDIA driver reports CUDA 13.0 support
│ │ ℹ GPU compute capability: 8.8
├ step  engine=speech-bubble-segmentation
│ ⚠ pipeline step failed: DriverError(CUDA_ERROR_NOT_FOUND, "error")  engine=speech-bubble-segmentation 
```

ZLUDA loaded with `LD_LIBRARY_PATH="[...]/zluda:$LD_LIBRARY_PATH" koharu_linux_x64`

ROCm:   7.2.2.
Koharu: 0.55.0
ZLUDA:  Version 6-preview.66

**Comment by 0fbcb238c0** [comment]
Troubleshot some more.

```
cuInit(Flags: 0) -> CUDA_SUCCESS
    Created trace directory ./koharu_linux_x64_2 
cuDriverGetVersion(driverVersion: 13000) -> CUDA_SUCCESS
cuInit(Flags: 0) -> CUDA_SUCCESS
cuDeviceGet(device: 0, ordinal: 0) -> CUDA_SUCCESS
cuDeviceGetAttribute(pi: 8, attrib: CU_DEVICE_ATTRIBUTE_COMPUTE_CAPABILITY_MAJOR, dev: 0) -> CUDA_SUCCESS
cuDeviceGetAttribute(pi: 8, attrib: CU_DEVICE_ATTRIBUTE_COMPUTE_CAPABILITY_MINOR, dev: 0) -> CUDA_SUCCESS
cuInit(Flags: 0) -> CUDA_SUCCESS
cuDeviceGet(device: 0, ordinal: 0) -> CUDA_SUCCESS
cuDevicePrimaryCtxRetain(pctx: 0x7fa9b822ecb0, dev: 0) -> CUDA_SUCCESS
cuDeviceGetAttribute(pi: 0, attrib: CU_DEVICE_ATTRIBUTE_MEMORY_POOLS_SUPPORTED, dev: 0) -> CUDA_SUCCESS
cuCtxGetCurrent(pctx: 0x0) -> CUDA_SUCCESS
cuCtxSetCurrent(ctx: 0x7fa9b822ecb0) -> CUDA_SUCCESS
cuCtxGetCurrent(pctx: 0x7fa9b822ecb0) -> CUDA_SUCCESS
cuCtxGetCurrent(pctx: 0x7fa9b822ecb0) -> CUDA_SUCCESS
cuCtxGetCurrent(pctx: 0x7fa9b822ecb0) -> CUDA_SUCCESS
cuDevicePrimaryCtxRelease_v2(dev: 0) -> CUDA_SUCCESS
```

Looks fine at first, but fails in koharu with
```
pipeline step failed: CublasError(CUBLAS_STATUS_INTERNAL_ERROR)  engine=speech-bubble-segmentation
```

**Comment by zachelnet** [comment]
Hi @0fbcb238c0,

Why: On Linux, the current ZLUDA runtime handling can lead to DriverError(CUDA_ERROR_NOT_FOUND) in the segmentation pipeline.

What changed / proposed: We likely need to adjust the ZLUDA runtime logic in crates/koharu-runtime/src/zluda.rs.

Tested on: Fedora 44, ROCm (RPM Fusion) with ROCm 7.1, using ZLUDA 7-preview.3.

I tested this in my fork on branch [feat/zluda-linux](https://github.com/zachelnet/koharu/tree/feat/zluda-linux), where the Linux + ZLUDA flow works.
